// USER
export const FOLLOW_USER = "FOLLOW_USER";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL";
export const FETCH_LEADERBOARD = "FETCH_LEADERBOARD";
export const FETCH_LEADERBOARD_SUCCESS = "FETCH_LEADERBOARD_SUCCESS";
export const FETCH_LEADERBOARD_FAIL = "FETCH_LEADERBOARD_FAIL";
